# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meltify < Formula
  desc "Export compact Nostr/SSH/MELT seed material from Ed25519 OpenSSH keys"
  homepage "https://github.com/ZenTenApp/meltify"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ZenTenApp/meltify/releases/download/v0.1.1/meltify_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "5c33a76c462585000738d4306ecbd6d170a851a7ba85dd85e123b9b6e61297e0"

      define_method(:install) do
        bin.install "meltify"
        bash_completion.install "completions/meltify.bash" => "meltify"
        zsh_completion.install "completions/meltify.zsh" => "_meltify"
        fish_completion.install "completions/meltify.fish"
        man1.install "manpages/meltify.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ZenTenApp/meltify/releases/download/v0.1.1/meltify_0.1.1_Darwin_arm64.tar.gz"
      sha256 "37ad8837055a657dc6abe2b79d647d8cced837f528630f0bcde1e0d6c43f7ccb"

      define_method(:install) do
        bin.install "meltify"
        bash_completion.install "completions/meltify.bash" => "meltify"
        zsh_completion.install "completions/meltify.zsh" => "_meltify"
        fish_completion.install "completions/meltify.fish"
        man1.install "manpages/meltify.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZenTenApp/meltify/releases/download/v0.1.1/meltify_0.1.1_Linux_x86_64.tar.gz"
      sha256 "47ac1f4f80acfc5343d86c4819e66164fbd93c8361dc9b8ef24a0a99818ab3f2"
      define_method(:install) do
        bin.install "meltify"
        bash_completion.install "completions/meltify.bash" => "meltify"
        zsh_completion.install "completions/meltify.zsh" => "_meltify"
        fish_completion.install "completions/meltify.fish"
        man1.install "manpages/meltify.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ZenTenApp/meltify/releases/download/v0.1.1/meltify_0.1.1_Linux_armv7.tar.gz"
      sha256 "f34406f74bf20124867be33df0bad0952de284ca85c52c7fe2bee28a42016f4b"
      define_method(:install) do
        bin.install "meltify"
        bash_completion.install "completions/meltify.bash" => "meltify"
        zsh_completion.install "completions/meltify.zsh" => "_meltify"
        fish_completion.install "completions/meltify.fish"
        man1.install "manpages/meltify.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZenTenApp/meltify/releases/download/v0.1.1/meltify_0.1.1_Linux_arm64.tar.gz"
      sha256 "4430eddffe7af111c36f8b589ffdda86bc1ecb04c8537df25e2953b9772d5f9c"
      define_method(:install) do
        bin.install "meltify"
        bash_completion.install "completions/meltify.bash" => "meltify"
        zsh_completion.install "completions/meltify.zsh" => "_meltify"
        fish_completion.install "completions/meltify.fish"
        man1.install "manpages/meltify.1.gz"
      end
    end
  end
end
