# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seedify < Formula
  desc "Convert SSH keys to BIP-39 seed phrases"
  homepage "https://github.com/ZenTenApp/seedify"
  version "1.31.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ZenTenApp/seedify/releases/download/v1.31.0/seedify_1.31.0_Darwin_x86_64.tar.gz"
      sha256 "5e88a05e1bc3745416404ae58b3a376b3f1284de4bd0fbab1639b64b5a24e127"

      define_method(:install) do
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ZenTenApp/seedify/releases/download/v1.31.0/seedify_1.31.0_Darwin_arm64.tar.gz"
      sha256 "3dd40e3cc4cb925831704a1321a3de7093d52567985a629d376d47dd8446c1ac"

      define_method(:install) do
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZenTenApp/seedify/releases/download/v1.31.0/seedify_1.31.0_Linux_x86_64.tar.gz"
      sha256 "b4f19e8db7dafcf8cc228096dabd924361895b4fd7e884281c41d3f440cda969"
      define_method(:install) do
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ZenTenApp/seedify/releases/download/v1.31.0/seedify_1.31.0_Linux_armv7.tar.gz"
      sha256 "66f46087594d799df6cac411ba2c0be5a766d10fa266e1c9799ed80ca7f47f57"
      define_method(:install) do
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZenTenApp/seedify/releases/download/v1.31.0/seedify_1.31.0_Linux_arm64.tar.gz"
      sha256 "e0af20ed03ca31c2953dd88f98657a046a613859158f6d4cf4543fdd8b6d2e19"
      define_method(:install) do
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
  end
end
