# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seedify < Formula
  desc "Convert SSH keys to BIP-39 seed phrases"
  homepage "https://github.com/ZenTenApp/seedify"
  version "1.29.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ZenTenApp/seedify/releases/download/v1.29.0/seedify_1.29.0_Darwin_x86_64.tar.gz"
      sha256 "4d0287225e87ac4a1fa38471c79370de4c23d360e9389b666e5e10424878d911"

      define_method(:install) do
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ZenTenApp/seedify/releases/download/v1.29.0/seedify_1.29.0_Darwin_arm64.tar.gz"
      sha256 "1aa225709a76829789773265780b589d9a190c3116c6569adc5cdec43352b34a"

      define_method(:install) do
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZenTenApp/seedify/releases/download/v1.29.0/seedify_1.29.0_Linux_x86_64.tar.gz"
      sha256 "f8cbb00420c4185ede61174d0fbe9d438ec36db7eb278c497135f021f63b388b"
      define_method(:install) do
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ZenTenApp/seedify/releases/download/v1.29.0/seedify_1.29.0_Linux_armv7.tar.gz"
      sha256 "1e9ef2116dd388dd6d44048b9bafac1c9cf34862eb1fcaac36cb63ddef3a40e6"
      define_method(:install) do
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZenTenApp/seedify/releases/download/v1.29.0/seedify_1.29.0_Linux_arm64.tar.gz"
      sha256 "37f5272687f01ec09adefeabda63f2e055c6e98f874e7c32d7f1e871208a97cc"
      define_method(:install) do
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
  end
end
